const crypto = require("crypto");

module.exports = {
  id: "013_proposal_seeds",
  description: "Seed default proposal template, sections, and test-type write-ups.",
  up(db) {
    const templateId = "builtin-proposal-default";

    db.prepare(`
      INSERT OR IGNORE INTO reporter_proposal_templates (id, name, description, template_type, is_builtin, sort_order, created_at, updated_at)
      VALUES (?, ?, ?, ?, 1, 0, unixepoch(), unixepoch())
    `).run(templateId, "Security Assessment Proposal", "Default proposal template for penetration testing and security assessment engagements.", "security_assessment");

    const sections = [
      { title: "Cover / Introduction", section_type: "markdown", content: "# {{title}}\\n\\nPrepared for **{{client_name}}**\\n\\n{{date}}", order_index: 0, is_required: 1 },
      { title: "Client and Contacts", section_type: "markdown", content: "## Client\\n\\n**{{client_name}}**\\n\\n**Primary Contact:** {{primary_contact_name}} ({{primary_contact_email}})\\n\\n## Prepared By\\n\\n{{prepared_by_name}}", order_index: 1, is_required: 1 },
      { title: "Understanding of Requirements", section_type: "markdown", content: "## Understanding of Requirements\\n\\nBased on our discussions, we understand the following requirements:", order_index: 2, is_required: 1 },
      { title: "Proposed Services", section_type: "markdown", content: "## Proposed Services\\n\\n{{test_type_inserts}}", order_index: 3, is_required: 1 },
      { title: "Scope of Work", section_type: "markdown", content: "## Scope of Work\\n\\n### In Scope\\n\\n### Authorised Targets\\n\\n### Testing Window", order_index: 4, is_required: 1 },
      { title: "Out of Scope", section_type: "markdown", content: "## Out of Scope\\n\\nThe following are explicitly excluded from this engagement:", order_index: 5, is_required: 0 },
      { title: "Methodology", section_type: "markdown", content: "## Methodology\\n\\nOur testing follows established industry methodologies and frameworks including OWASP, PTES, OSSTMM, and NIST SP 800-115.", order_index: 6, is_required: 0 },
      { title: "Rules of Engagement and Restrictions", section_type: "markdown", content: "## Rules of Engagement\\n\\n### Authorised Actions\\n\\n### Restricted Actions\\n\\n### Deconfliction", order_index: 7, is_required: 0 },
      { title: "Client Responsibilities and Prerequisites", section_type: "markdown", content: "## Client Responsibilities\\n\\n{{client_requirements_insert}}", order_index: 8, is_required: 0 },
      { title: "Consultant Requirements", section_type: "markdown", content: "## Consultant Requirements\\n\\n{{consultant_requirements_insert}}", order_index: 9, is_required: 0 },
      { title: "Time Allocation", section_type: "markdown", content: "## Time Allocation\\n\\n| Phase | Days |\\n|-------|------|\\n| Scoping and Planning | {{scoping_days}} |\\n| Testing | {{testing_days}} |\\n| Analysis and Reporting | {{reporting_days}} |\\n| **Total** | **{{estimated_days}}** |", order_index: 10, is_required: 0 },
      { title: "Delivery Schedule", section_type: "markdown", content: "## Delivery Schedule\\n\\n- **Testing Start:** {{start_date}}\\n- **Testing End:** {{end_date}}\\n- **Draft Report:** {{draft_date}}\\n- **Final Report:** {{final_date}}", order_index: 11, is_required: 0 },
      { title: "Deliverables", section_type: "markdown", content: "## Deliverables\\n\\n1. Executive summary\\n2. Detailed technical findings with evidence\\n3. Risk ratings and remediation guidance\\n4. Re-test confirmation of resolved findings (if requested)", order_index: 12, is_required: 0 },
      { title: "Commercial Terms", section_type: "markdown", content: "## Commercial Terms\\n\\n**Total Fee:** {{quoted_value}}\\n\\n**Payment Terms:** Net 30 days from invoice date.\\n\\n**Valid Until:** {{valid_until}}", order_index: 13, is_required: 0 },
      { title: "Acceptance and Next Steps", section_type: "markdown", content: "## Acceptance and Next Steps\\n\\n1. Review and sign this proposal\\n2. Provide authorised target list and credentials\\n3. Schedule kick-off meeting\\n4. Commence testing per agreed schedule", order_index: 14, is_required: 0 },
    ];

    const insertSection = db.prepare(`
      INSERT OR IGNORE INTO reporter_proposal_template_sections (id, template_id, title, section_type, content, order_index, is_required, is_builtin, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, 1, unixepoch(), unixepoch())
    `);

    for (const s of sections) {
      insertSection.run(crypto.randomBytes(16).toString("base64url"), templateId, s.title, s.section_type, s.content, s.order_index, s.is_required);
    }

    const testTypes = [
      { type: "external", name: "External Penetration Testing", methodology: "External penetration testing simulates an attack from outside the organisation's network perimeter. We identify exposed services, enumerate vulnerabilities, and attempt to gain unauthorised access to internal systems through internet-facing assets.", scope: "All externally accessible IP ranges, domains, and web applications. Includes DNS enumeration, port scanning, service identification, and vulnerability exploitation.", deliverables: "All identified external vulnerabilities, evidence of exploitation, screenshots of access gained, and remediation recommendations.", client_reqs: "Written authorisation for all external IP ranges and domains. Network diagrams of external perimeter. Point of contact for deconfliction during testing.", consultant_reqs: "No prior knowledge of internal network architecture (black-box approach). Testing performed from off-network locations.", assumptions: "Testing occurs during agreed windows. No denial-of-service attacks will be performed. Testing will not intentionally disrupt production services.", restrictions: "No DoS/DDoS testing. No social engineering unless explicitly scoped. No testing of third-party hosted services without written consent." },
      { type: "internal", name: "Internal Penetration Testing", methodology: "Internal penetration testing simulates an attacker who has gained access to the internal network. Starting from a standard user position, we attempt to escalate privileges, move laterally, and access sensitive systems and data.", scope: "Internal network segments, Active Directory environment, file shares, databases, and internal applications. May include VLAN hopping and network segmentation testing.", deliverables: "Lateral movement paths, privilege escalation chains, credential harvesting results, and access to sensitive data demonstrated.", client_reqs: "Network access (wired or wireless). A standard user account (non-admin). Network architecture documentation. Authorisation for all target subnets.", consultant_reqs: "Testing laptop with standard tools. VPN or on-site access as agreed.", assumptions: "Starting position is a standard domain user. Testing will not intentionally corrupt databases or delete data. Backups are in place for critical systems.", restrictions: "No modification of production data. No creation of persistent backdoors. All test accounts and changes cleaned up after engagement." },
      { type: "webapp", name: "Web Application Penetration Testing", methodology: "Web application penetration testing follows the OWASP Testing Guide to identify vulnerabilities including injection flaws, broken authentication, sensitive data exposure, and misconfigured security controls.", scope: "All in-scope web applications, APIs, and associated backend services. Includes authentication flows, session management, input validation, and business logic testing.", deliverables: "All identified vulnerabilities mapped to OWASP Top 10 categories, proof-of-concept exploits, severity ratings, and detailed remediation guidance.", client_reqs: "Test accounts at different privilege levels. Application documentation and API specifications. Staging/test environment preferred over production.", consultant_reqs: "Application testing tools. Browser-based testing and automated scanning capabilities.", assumptions: "Testing performed against agreed application versions. Staging environment mirrors production where possible. Rate limiting may apply.", restrictions: "No testing against production without explicit written approval. No automated scanning at destructive concurrency levels." },
      { type: "cloud", name: "Cloud Security Review", methodology: "Cloud security review assesses the configuration and security posture of cloud environments across IaaS, PaaS, and SaaS services. We evaluate identity and access management, network security, data protection, logging, and compliance against CIS benchmarks and vendor best practices.", scope: "Cloud provider consoles, IAM configurations, network security groups, storage accounts, compute instances, and monitoring configurations.", deliverables: "Misconfigurations identified, CIS benchmark compliance status, privilege escalation paths, and remediation priorities.", client_reqs: "Read-only access to cloud management consoles. Inventory of cloud resources. Architecture documentation. Relevant compliance requirements.", consultant_reqs: "Cloud security assessment tools and scripts. Access to cloud provider APIs.", assumptions: "Review covers configuration, not application-layer vulnerabilities. Assessment based on point-in-time snapshot.", restrictions: "No changes to cloud configurations. No deletion or modification of resources. Read-only access only." },
      { type: "build_review", name: "Build Review", methodology: "Build review (source code review) examines application source code to identify security vulnerabilities before deployment. We review authentication mechanisms, input handling, cryptographic implementations, and secure coding practices.", scope: "Application source code repositories, build pipelines, dependency manifests, and configuration files.", deliverables: "Code-level vulnerability findings with file and line references, secure coding recommendations, and dependency vulnerability analysis.", client_reqs: "Access to source code repositories. Build instructions and environment setup. List of critical business logic components.", consultant_reqs: "Static analysis tools and manual review expertise.", assumptions: "Code review covers security-relevant code paths. Testing environment provided for verification.", restrictions: "No code modifications. Findings reported through agreed disclosure process." },
      { type: "wireless", name: "Wireless Assessment", methodology: "Wireless assessment evaluates the security of Wi-Fi networks including corporate, guest, and IoT networks. We test for weak encryption, rogue access points, captive portal bypasses, and wireless segmentation issues.", scope: "All in-scope wireless networks, access points, wireless controllers, and associated authentication mechanisms (WPA2-Enterprise, captive portals).", deliverables: "Wireless network inventory, encryption strength analysis, rogue device findings, and segmentation verification.", client_reqs: "Authorisation to test all wireless networks. List of authorised SSIDs. Wireless architecture documentation.", consultant_reqs: "Wireless testing equipment. Proximity to physical locations for signal testing.", assumptions: "Testing performed during agreed windows. No intentional jamming of wireless signals.", restrictions: "No interference with production wireless services. No connection to unauthorised networks." },
      { type: "configuration_review", name: "Configuration Review", methodology: "Configuration review examines system and application configurations against security benchmarks. We assess operating systems, databases, web servers, and middleware for insecure defaults and deviations from hardening standards.", scope: "Server configurations, database settings, application server configurations, network device configurations, and security policy settings.", deliverables: "Configuration findings mapped to CIS or vendor benchmarks, risk ratings, and hardening recommendations.", client_reqs: "Read-only access to system configurations. Current hardening standards or policies. Inventory of systems in scope.", consultant_reqs: "Configuration review scripts and benchmark tools.", assumptions: "Review covers configuration only, not operational security testing. Based on current configuration snapshot.", restrictions: "No changes to system configurations. Read-only access only." },
      { type: "assumed_breach", name: "Assumed Breach Assessment", methodology: "Assumed breach assessment starts from the premise that an attacker has already compromised an initial foothold. We test detection capabilities, lateral movement opportunities, and response procedures from a post-compromise position.", scope: "Internal network, endpoint detection systems, Active Directory, credential stores, and security monitoring infrastructure.", deliverables: "Attack paths from assumed breach point, detection gap analysis, credential exposure assessment, and response effectiveness evaluation.", client_reqs: "Pre-staged breach scenario (compromised workstation or user account). SOC team awareness of exercise window. Escalation contact for deconfliction.", consultant_reqs: "Post-exploitation tooling. Active Directory attack tools. Custom payload development capability.", assumptions: "Initial breach scenario is pre-agreed and staged. Blue team is aware testing is occurring but not of specific techniques.", restrictions: "No actions that trigger real incident response. All activity logged and available for review. Immediate stand-down if real compromise suspected." },
      { type: "red_team", name: "Red Team Assessment", methodology: "Red team assessments simulate real-world adversary behaviour using tactics, techniques, and procedures (TTPs) aligned with the MITRE ATT&K framework. Testing includes reconnaissance, initial access, execution, persistence, privilege escalation, and objective fulfilment.", scope: "Full-scope testing across external, internal, physical, and social engineering vectors as agreed. Objectives defined to test people, processes, and technology.", deliverables: "Attack narrative with full TTP chain, detection gaps, strategic recommendations, and lessons learned for blue team improvement.", client_reqs: "Clearly defined rules of engagement. Authorised target list. Deconfliction and escalation contacts. Physical access authorisation if in scope. Agreement on social engineering scope and boundaries.", consultant_reqs: "Full red team capability including social engineering, physical security testing, and custom tooling development.", assumptions: "Testing occurs over extended engagement period. Blue team operates normally. Findings may reveal critical security gaps.", restrictions: "No actions outside agreed ROE. No testing of individuals not explicitly authorised. Immediate disclosure of critical findings." },
      { type: "custom", name: "Generic Security Assessment", methodology: "Custom security assessment tailored to specific requirements. Testing methodology will be agreed during scoping to address the unique security concerns and objectives defined by the client.", scope: "To be defined during scoping phase based on client requirements and objectives.", deliverables: "Assessment findings, risk analysis, and recommendations tailored to the specific engagement objectives.", client_reqs: "Detailed requirements and objectives. Access to relevant systems and documentation. Points of contact for technical queries.", consultant_reqs: "Flexible testing capability to address agreed scope.", assumptions: "Scope and methodology agreed before testing commences.", restrictions: "As defined in the agreed scope and rules of engagement." },
    ];

    const insertType = db.prepare(`
      INSERT OR IGNORE INTO reporter_test_type_templates (id, test_type, name, description, methodology_writeup, scope_guidance, deliverables, client_requirements, consultant_requirements, assumptions, restrictions, is_builtin, sort_order, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, unixepoch(), unixepoch())
    `);

    testTypes.forEach((t, i) => {
      insertType.run(crypto.randomBytes(16).toString("base64url"), t.type, t.name, "", t.methodology, t.scope, t.deliverables, t.client_reqs, t.consultant_reqs, t.assumptions, t.restrictions, i);
    });
  },
};
